apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-microservice

spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataset-microservice
  template:
    metadata:
      labels:
        app: dataset-microservice
    spec:
      containers:
      - name: dataset-microservice
        image: ghcr.io/mickymots/dataset-microservice/dataset-microservice-image:develop
        ports:
        - containerPort: 5000                       #+
          name: http                                #+

---
kind: Service             #+
apiVersion: v1            #+
metadata:                 #+
  name: dataset-loadbalancer     #+
spec:                     #+
  selector:               #+
    app: dataset-microservice            #+
  ports:                  #+
  - protocol: TCP         #+
    targetPort: 5000      #+
    port: 80              #+
    name: http            #+
  type: LoadBalancer      #+