apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataset-microservice

spec:
  replicas: 2
  selector:
    matchLabels:
      app: dataset-microservice
  template:
    metadata:
      labels:
        app: dataset-microservice
    spec:
      containers:
      - name: dataset-microservice
        image: singhamitprakash/dataset-microservice:latest
        ports:
        - containerPort: 5000                       #+
          name: http                                #+
        - containerPort: 22                         #+
          name: ssh         